### ISSUE TITLE
missing compile required lib

### ISSUE THREAD

**Issue by hyperpainkiller** [Riborok/Remote-Desktop-WinAPI#1]
Hi, really nice of your remote desktop code, but it seems that the repo src don't have some depend lib, such as the Crypto++, and may be something else.

**Comment by Riborok** [comment]
I thought everyone would compile the libraries themselves, but I made a commit with the necessary libraries. You just need to unzip the libs.rar (I adjusted the project settings so you don’t need to make any changes after unzipping)

**Comment by hyperpainkiller** [comment]
That's so great, Thank you very much. I've just clone and read your code untill now, late at 1 clock midnight in china, your code is great and easy to unstand. i will try the newly update lib.zip after get up today. maybe some lib cannot used directly because i am using the vs2015, without c++17 support. I will handle it myself

**Comment by Riborok** [comment]
Thanks for the feedback! I'm glad that the code is clear
